name: Go
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.x'
      - name: Install dependencies
        run: go get -v ./...
      - name: Build
        run: go build -v ./...
      - name: Unit Tests
        run: go test -v -short ./...
      - name: Integration Tests
        run: go test -v -run Integration ./...
